import { Microscope, Dna, Brain, FlaskConical, Target, TrendingUp } from "lucide-react";

export function AboutBioinformatics() {
  return (
    <section className="container mx-auto px-4 py-20">
      {/* Main Introduction */}
      <div className="max-w-4xl mx-auto text-center mb-16">
        <span className="inline-block px-4 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium mb-6">
          Understanding Bioinformatics
        </span>
        <h2 className="text-4xl md:text-5xl font-bold tracking-tight mb-6">
          The Science of Decoding Life's Blueprint
        </h2>
        <p className="text-xl text-muted-foreground leading-relaxed mb-8">
          Bioinformatics sits at the intersection of biology, computer science, and mathematics, 
          providing the computational infrastructure to analyze the massive datasets generated by 
          modern molecular biology. From sequencing entire genomes to predicting protein structures, 
          bioinformatics transforms raw biological data into actionable scientific insights.
        </p>
      </div>

      {/* Featured Image Section */}
      <div className="relative mb-20 rounded-3xl overflow-hidden">
        <div className="relative h-[400px] w-full">
          <img 
            src="https://images.unsplash.com/photo-1559757175-5700dde675bc?w=1920&auto=format&fit=crop"
            alt="DNA research and genome sequencing visualization"
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-background/90 via-background/60 to-transparent" />
          <div className="absolute inset-0 flex items-center">
            <div className="max-w-2xl px-8 md:px-16">
              <h3 className="text-3xl font-bold mb-4">
                Transforming Healthcare Through Data
              </h3>
              <p className="text-lg text-muted-foreground mb-6">
                The Human Genome Project, completed in 2003, sequenced all 3.2 billion base pairs 
                of human DNA. Today, advances in next-generation sequencing allow us to sequence 
                an entire genome in less than 24 hours for under $1,000—a task that once cost 
                $2.7 billion and took 13 years.
              </p>
              <div className="flex gap-6">
                <div>
                  <div className="text-3xl font-bold text-primary">3.2B+</div>
                  <div className="text-sm text-muted-foreground">Base Pairs in Human Genome</div>
                </div>
                <div>
                  <div className="text-3xl font-bold text-primary">&lt;$1K</div>
                  <div className="text-sm text-muted-foreground">Cost to Sequence a Genome</div>
                </div>
                <div>
                  <div className="text-3xl font-bold text-primary">24hrs</div>
                  <div className="text-sm text-muted-foreground">Sequencing Time</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Core Fields Grid */}
      <div className="mb-20">
        <h3 className="text-2xl font-bold text-center mb-12">Core Fields of Bioinformatics</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {[
            {
              icon: Dna,
              title: "Genomics & Transcriptomics",
              description: "Analyze entire genomes and gene expression patterns. Identify variants associated with diseases, understand gene regulation, and explore evolutionary relationships through comparative genomics.",
              color: "text-blue-500 bg-blue-500/10"
            },
            {
              icon: FlaskConical,
              title: "Proteomics & Structural Biology",
              description: "Study protein expression, structure, and function. Tools like AlphaFold have revolutionized our ability to predict 3D protein structures, accelerating drug discovery and understanding of molecular mechanisms.",
              color: "text-green-500 bg-green-500/10"
            },
            {
              icon: Brain,
              title: "Machine Learning & AI",
              description: "Apply deep learning and statistical models to biological data. From predicting drug-target interactions to analyzing medical images, AI is reshaping how we approach complex biological questions.",
              color: "text-purple-500 bg-purple-500/10"
            },
            {
              icon: Microscope,
              title: "Metagenomics & Microbiome",
              description: "Explore microbial communities in their natural environments. Understanding the human microbiome has revealed its crucial role in health, disease, and even mental health conditions.",
              color: "text-orange-500 bg-orange-500/10"
            },
            {
              icon: Target,
              title: "Drug Discovery & Development",
              description: "Accelerate pharmaceutical research through virtual screening, molecular docking, and ADMET prediction. Bioinformatics can reduce drug development time from 12 years to just a few years.",
              color: "text-red-500 bg-red-500/10"
            },
            {
              icon: TrendingUp,
              title: "Systems Biology",
              description: "Model complex biological systems as integrated networks. Understand how genes, proteins, and metabolites interact to produce emergent behaviors in health and disease.",
              color: "text-cyan-500 bg-cyan-500/10"
            }
          ].map((field, idx) => (
            <div key={idx} className="glass-card p-8 hover:shadow-xl transition-all group">
              <div className={`w-14 h-14 rounded-2xl ${field.color} flex items-center justify-center mb-6 group-hover:scale-110 transition-transform`}>
                <field.icon className="w-7 h-7" />
              </div>
              <h4 className="text-xl font-bold mb-3">{field.title}</h4>
              <p className="text-muted-foreground leading-relaxed">{field.description}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Why Learn Bioinformatics */}
      <div className="glass-card p-8 md:p-12 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-1/2 h-full bg-gradient-to-l from-primary/5 to-transparent" />
        <div className="relative grid md:grid-cols-2 gap-12 items-center">
          <div>
            <h3 className="text-3xl font-bold mb-6">Why Learn Bioinformatics in 2024?</h3>
            <div className="space-y-4 text-muted-foreground">
              <p className="leading-relaxed">
                The global bioinformatics market is projected to reach <span className="text-foreground font-semibold">$24.7 billion by 2030</span>, 
                growing at a CAGR of 13.4%. This explosive growth is driven by the exponential increase in biological data 
                from next-generation sequencing, proteomics, and single-cell technologies.
              </p>
              <p className="leading-relaxed">
                Organizations across pharmaceuticals, healthcare, agriculture, and biotechnology are 
                desperately seeking professionals who can bridge the gap between wet-lab biology and 
                computational analysis. With programming skills in Python and R, combined with biological 
                knowledge, you'll be positioned at the forefront of scientific innovation.
              </p>
              <p className="leading-relaxed">
                Modern bioinformatics is no longer confined to academia. Companies like Illumina, 
                Genentech, 23andMe, and countless startups are revolutionizing healthcare through 
                personalized medicine, cancer genomics, and AI-driven drug discovery—all requiring 
                skilled bioinformaticians.
              </p>
            </div>
          </div>
          <div className="space-y-6">
            <img 
              src="https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&auto=format&fit=crop"
              alt="Modern laboratory with DNA analysis equipment"
              className="rounded-2xl shadow-2xl"
            />
            <div className="grid grid-cols-2 gap-4">
              <div className="glass-card p-4 text-center">
                <div className="text-2xl font-bold text-primary">$24.7B</div>
                <div className="text-xs text-muted-foreground">Market Size by 2030</div>
              </div>
              <div className="glass-card p-4 text-center">
                <div className="text-2xl font-bold text-primary">13.4%</div>
                <div className="text-xs text-muted-foreground">Annual Growth Rate</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
