/**
 * Elasticsearch Index Mappings
 * 
 * Explicit mappings for all searchable content:
 * - Tools
 * - Blog Posts
 * - Courses
 * - Jobs
 * 
 * Using plain objects for Elasticsearch v9.x compatibility
 */

// Custom analyzers for bioinformatics content
export const analysisSettings = {
  analysis: {
    analyzer: {
      // Autocomplete analyzer with edge n-grams
      autocomplete: {
        type: "custom",
        tokenizer: "standard",
        filter: ["lowercase", "autocomplete_filter"],
      },
      // Search analyzer for matching autocomplete
      autocomplete_search: {
        type: "custom",
        tokenizer: "standard",
        filter: ["lowercase"],
      },
      // Scientific terms analyzer
      scientific: {
        type: "custom",
        tokenizer: "standard",
        filter: ["lowercase", "scientific_synonyms"],
      },
    },
    filter: {
      autocomplete_filter: {
        type: "edge_ngram",
        min_gram: 2,
        max_gram: 20,
      },
      scientific_synonyms: {
        type: "synonym",
        synonyms: [
          "ngs, next-generation sequencing, next generation sequencing",
          "rna-seq, rnaseq, rna sequencing",
          "dna-seq, dnaseq, dna sequencing",
          "wgs, whole genome sequencing",
          "wes, whole exome sequencing",
          "chip-seq, chipseq, chromatin immunoprecipitation sequencing",
          "atac-seq, atacseq",
          "scrna-seq, scrnaseq, single cell rna sequencing",
          "blast, basic local alignment search",
          "bwa, burrows wheeler aligner",
          "gatk, genome analysis toolkit",
          "ml, machine learning",
          "dl, deep learning",
          "ai, artificial intelligence",
        ],
      },
    },
  },
};

// Tools index mapping
export const toolsMapping = {
  properties: {
    id: { type: "keyword" },
    name: {
      type: "text",
      analyzer: "scientific",
      fields: {
        keyword: { type: "keyword" },
        autocomplete: { type: "text", analyzer: "autocomplete", search_analyzer: "autocomplete_search" },
      },
    },
    slug: { type: "keyword" },
    description: {
      type: "text",
      analyzer: "scientific",
    },
    content: {
      type: "text",
      analyzer: "scientific",
    },
    categoryId: { type: "keyword" },
    categoryName: {
      type: "text",
      fields: { keyword: { type: "keyword" } },
    },
    categorySlug: { type: "keyword" },
    pricing: { type: "keyword" },
    url: { type: "keyword", index: false },
    image: { type: "keyword", index: false },
    published: { type: "boolean" },
    featured: { type: "boolean" },
    createdAt: { type: "date" },
    updatedAt: { type: "date" },
    suggest: {
      type: "completion",
      analyzer: "simple",
      preserve_separators: true,
      preserve_position_increments: true,
      max_input_length: 50,
    },
  },
};

// Posts index mapping
export const postsMapping = {
  properties: {
    id: { type: "keyword" },
    title: {
      type: "text",
      analyzer: "scientific",
      fields: {
        keyword: { type: "keyword" },
        autocomplete: { type: "text", analyzer: "autocomplete", search_analyzer: "autocomplete_search" },
      },
    },
    slug: { type: "keyword" },
    excerpt: { type: "text", analyzer: "scientific" },
    content: { type: "text", analyzer: "scientific" },
    categoryId: { type: "keyword" },
    categoryName: {
      type: "text",
      fields: { keyword: { type: "keyword" } },
    },
    categorySlug: { type: "keyword" },
    image: { type: "keyword", index: false },
    published: { type: "boolean" },
    isAutoGenerated: { type: "boolean" },
    createdAt: { type: "date" },
    updatedAt: { type: "date" },
    suggest: {
      type: "completion",
      analyzer: "simple",
    },
  },
};

// Courses index mapping
export const coursesMapping = {
  properties: {
    id: { type: "keyword" },
    title: {
      type: "text",
      analyzer: "scientific",
      fields: {
        keyword: { type: "keyword" },
        autocomplete: { type: "text", analyzer: "autocomplete", search_analyzer: "autocomplete_search" },
      },
    },
    slug: { type: "keyword" },
    description: { type: "text", analyzer: "scientific" },
    categoryId: { type: "keyword" },
    categoryName: {
      type: "text",
      fields: { keyword: { type: "keyword" } },
    },
    level: { type: "keyword" },
    provider: { type: "keyword" },
    url: { type: "keyword", index: false },
    image: { type: "keyword", index: false },
    published: { type: "boolean" },
    createdAt: { type: "date" },
    updatedAt: { type: "date" },
    suggest: {
      type: "completion",
      analyzer: "simple",
    },
  },
};

// Export all mappings
export const indexMappings = {
  tools: toolsMapping,
  posts: postsMapping,
  courses: coursesMapping,
};
