import Link from "next/link";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { 
  Dna, 
  Terminal, 
  Database, 
  BookOpen, 
  ArrowRight, 
  Microscope, 
  Code2,
  Layers
} from "lucide-react";

export const metadata = {
  title: "Beginner's Guide to Bioinformatics | BioinformaticsHub",
  description: "A comprehensive starting point for biologists and computer scientists entering the field of bioinformatics.",
};

export default function BeginnerGuidePage() {
  return (
    <div className="min-h-screen pb-20">
      <PageHeader 
        title="Beginner's Guide"
        subtitle="Your roadmap to mastering the intersection of biology and computer science."
        backgroundImage="https://images.unsplash.com/photo-1576086213369-97a306d3d957?w=1600&auto=format&fit=crop&q=80"
      />

      <div className="container mx-auto px-4 -mt-10 relative z-10 space-y-12">
        
        {/* Intro Section */}
        <div className="glass-card p-8 md:p-12 rounded-3xl border border-white/10 shadow-xl">
          <div className="max-w-3xl mx-auto text-center space-y-6">
            <h2 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-purple-400">
              What is Bioinformatics?
            </h2>
            <p className="text-lg text-muted-foreground leading-relaxed">
              Bioinformatics is an interdisciplinary field that develops methods and software tools for understanding biological data. As an intersection of computer science, biology, and statistics, it is essential for analyzing and interpreting the vast amounts of biological data generated by modern technologies like Next-Generation Sequencing (NGS).
            </p>
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          
          {/* For Biologists */}
          <div className="glass-card p-8 rounded-3xl border border-white/10 hover:border-primary/50 transition-colors">
            <div className="flex items-center gap-4 mb-6">
              <div className="w-12 h-12 rounded-xl bg-green-500/10 text-green-500 flex items-center justify-center">
                <Microscope className="w-6 h-6" />
              </div>
              <h3 className="text-2xl font-bold">I am a Biologist</h3>
            </div>
            <p className="text-muted-foreground mb-6">
              You understand the science, but the command line looks scary. Here&apos;s how to bridge the gap:
            </p>
            <ul className="space-y-4">
              <li className="flex gap-3">
                <Terminal className="w-5 h-5 text-primary shrink-0" />
                <span><strong>Learn the Terminal:</strong> Get comfortable with Linux/Unix. It&apos;s the language of bioinformatics tools.</span>
              </li>
              <li className="flex gap-3">
                <Code2 className="w-5 h-5 text-primary shrink-0" />
                <span><strong>Pick a Language:</strong> Python is the best starter. It&apos;s readable and has powerful bio-libraries.</span>
              </li>
              <li className="flex gap-3">
                <Database className="w-5 h-5 text-primary shrink-0" />
                <span><strong>Understand Data Formats:</strong> Learn what FASTQ, BAM, and VCF files actually contain.</span>
              </li>
            </ul>
             <div className="mt-8">
              <Link href="/resources/paths">
                <Button variant="outline" className="w-full gap-2">
                  View Biologist Learning Path <ArrowRight className="w-4 h-4" />
                </Button>
              </Link>
            </div>
          </div>

          {/* For Computer Scientists */}
          <div className="glass-card p-8 rounded-3xl border border-white/10 hover:border-purple-500/50 transition-colors">
            <div className="flex items-center gap-4 mb-6">
              <div className="w-12 h-12 rounded-xl bg-purple-500/10 text-purple-500 flex items-center justify-center">
                <Code2 className="w-6 h-6" />
              </div>
              <h3 className="text-2xl font-bold">I am a Developer</h3>
            </div>
            <p className="text-muted-foreground mb-6">
              You can code, but you don't know a gene from a genome. Here&apos;s your entry point:
            </p>
            <ul className="space-y-4">
              <li className="flex gap-3">
                <Dna className="w-5 h-5 text-purple-400 shrink-0" />
                <span><strong>Central Dogma:</strong> DNA → RNA → Protein. Understand this foundation first.</span>
              </li>
              <li className="flex gap-3">
                <Layers className="w-5 h-5 text-purple-400 shrink-0" />
                <span><strong> sequencing Technologies:</strong> Learn how data is generated (Ilumina, Nanopore).</span>
              </li>
              <li className="flex gap-3">
                <BookOpen className="w-5 h-5 text-purple-400 shrink-0" />
                <span><strong> biological Databases:</strong> Explore NCBI, Ensembl, and UCSC Genome Browser.</span>
              </li>
            </ul>
            <div className="mt-8">
              <Link href="/resources/paths">
                <Button variant="outline" className="w-full gap-2">
                  View Developer Learning Path <ArrowRight className="w-4 h-4" />
                </Button>
              </Link>
            </div>
          </div>

        </div>

        {/* Essential Concepts Grid */}
        <div>
           <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
            <BookOpen className="w-6 h-6 text-primary" />
            Essential Concepts to Master
          </h2>
          <div className="grid md:grid-cols-3 gap-6">
            {[
              { title: "Sequence Alignment", desc: "Comparing DNA/protein sequences to identify regions of similarity." },
              { title: "Gene Expression", desc: "Quantifying how much a gene is 'turned on' in different conditions." },
              { title: "Variant Calling", desc: "Finding differences between an individual's genome and a reference." },
              { title: "Phylogenetics", desc: "Studying evolutionary relationships among biological entities." },
              { title: "Structural Biology", desc: "Predicting the 3D structure of proteins/macromolecules." },
              { title: "Metagenomics", desc: "Analyzing genetic material recovered directly from environmental samples." },
            ].map((item, idx) => (
              <div key={idx} className="bg-white/5 border border-white/10 p-6 rounded-2xl hover:bg-white/10 transition-colors">
                <h4 className="font-semibold text-lg mb-2 text-primary/80">{item.title}</h4>
                <p className="text-sm text-muted-foreground">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Next Steps CTA */}
        <div className="glass-card p-12 rounded-3xl border border-white/10 text-center space-y-6 bg-gradient-to-b from-transparent to-primary/5">
          <h2 className="text-3xl font-bold">Ready to Dive Deeper?</h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            The best way to learn is by doing. Explore our directory of tools or pick a structured learning path to start your journey today.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/directory">
              <Button size="lg" className="rounded-full px-8">
                Explore Tools
              </Button>
            </Link>
            <Link href="/resources/paths">
              <Button size="lg" variant="secondary" className="rounded-full px-8">
                View Learning Paths
              </Button>
            </Link>
          </div>
        </div>

      </div>
    </div>
  );
}
